create table USERR(
  ID INTEGER PRIMARY KEY,
  NAME VARCHAR(20),
  PASSWORD VARCHAR(20)
);

INSERT INTO USERR VALUES(1,'POPOV','123DE');

CREATE TABLE ATTEMPT(
  ID INTEGER PRIMARY KEY,
  ATT_COUNT INTEGER,
  USER_ID INTEGER REFERENCES USERR(ID) ON DELETE CASCADE
);

INSERT INTO ATTEMPT VALUES(1,10,1);